[tool.black]
line-length = 119
target-version = ['py37']
include = '\.pyi?$'
exclude = '''
# A regex preceded with ^/ will apply only to files and directories
# in the root of the project.
^/(
  (
      \.eggs         # exclude a few common directories in the
    | \.git          # root of the project
    | \.hg
    | \.mypy_cache
    | \.tox
    | \.venv
    | _build
    | buck-out
    | build
    | dist
    | .*\b(migrations)\b.*
    | env
    | venv
    | node_modules
    | requirements
    | design_system
    | tmp
  )/
)
'''
